export const USER_LOGIN_ACTION = "USER_LOGIN_ACTION";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const REGISTER_USER = "REGISTER_USER";
export const GETTER_TOKEN = "GETTER_TOKEN";
export const GETTER_USER_INFO = "GETTER_USER_INFO";
export const PUT_USER_INFO = "PUT_USER_INFO";
